version: '3.4'
services:
  duckling-server:
    image: rasa/duckling:latest
    ports:
    - 8000:8000
    networks:
    - all

  rasa-server:
    image: rasa-server-okteto:latest
    build: './'
    restart: always
    volumes:
    - ./data:/app/data
    - ./actions:/app/actions
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
    ports:
    - '5006:5005'
    public: true
    working_dir: "/app/"
    networks:
    - all

  rasa-actions:
    image: rasa-server-okteto:latest
    build: './'
    restart: always
    volumes:
    - ./actions:/app/actions
    command: ["rasa", "run", "actions"]
    ports:
    - '5055:5055'
    working_dir: "/app/"
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"